services:
  - type: web
    name: medical-report-analyzer
    env: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false